apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  name: qwen3-8b-cachi-llmd
  namespace: llmd-demo
  annotations:
    opendatahub.io/model-type: generative
    openshift.io/display-name: qwen3-8b-cachi-llmd
    security.opendatahub.io/enable-auth: 'false'
spec:
  replicas: 3
  model:
    # uri: pvc://model-storage/RedHatAI/Qwen3-8B-FP8-dynamic
    uri: oci://registry.redhat.io/rhelai1/modelcar-qwen3-8b-fp8-dynamic:1.5
    name: RedHatAI/Qwen3-8B-FP8-dynamic
  router:
    scheduler:
      template:
        containers:
          - name: main
            env:
              - name: TOKENIZER_CACHE_DIR
                value: /tmp/tokenizer-cache
              - name: HF_HOME
                value: /tmp/tokenizer-cache
              - name: TRANSFORMERS_CACHE
                value: /tmp/tokenizer-cache
              - name: XDG_CACHE_HOME
                value: /tmp
              - name: LOCAL_TOKENIZER_DIR
                value: /tmp
            args:
              - --pool-group
              - inference.networking.x-k8s.io
              - '--pool-name'
              - '{{ ChildName .ObjectMeta.Name `-inference-pool` }}'
              - '--pool-namespace'
              - '{{ .ObjectMeta.Namespace }}'
              - '--zap-encoder'
              - json
              - '--grpc-port'
              - '9002'
              - '--grpc-health-port'
              - '9003'
              - '--secure-serving'
              - '--model-server-metrics-scheme'
              - https
              - '--config-text'
              - |
                apiVersion: inference.networking.x-k8s.io/v1alpha1
                kind: EndpointPickerConfig
                plugins:
                - type: single-profile-handler
                - type: queue-scorer
                - type: kv-cache-utilization-scorer
                - type: precise-prefix-cache-scorer
                schedulingProfiles:
                - name: default
                  plugins:
                  - pluginRef: queue-scorer
                    weight: 2
                  - pluginRef: kv-cache-utilization-scorer
                    weight: 2
                  - pluginRef: precise-prefix-cache-scorer
                    weight: 3
            volumeMounts:
              - name: tokenizer-cache
                mountPath: /tmp/
              - name: cachi-cache
                mountPath: /cachi2/
        volumes:
          - name: tokenizer-cache
            emptyDir: {}
          - name: cachi-cache
            emptyDir: {}
    route: {}
    gateway: {}
  template:
    nodeSelector:
      node.kubernetes.io/instance-type: "g6.2xlarge"
    # tolerations:
    #   - key: "nvidia.com/gpu"
    #     operator: "Exists"
    #     effect: "NoSchedule"
    # tolerations:
    # - key: "nvidia.com/gpu"
    #   operator: "Equal"
    #   value: "NVIDIA-A10G-SHARED"
    #   effect: "NoSchedule"
    containers:
      - name: main
        env:
          - name: VLLM_ADDITIONAL_ARGS
            value: "--disable-uvicorn-access-log --max-model-len=10000 --gpu-memory-utilization=0.9 --enable-prefix-caching"
        resources:
          limits:
            cpu: '1'
            memory: 8Gi
            nvidia.com/gpu: "1"
          requests:
            cpu: '1'
            memory: 8Gi
            nvidia.com/gpu: "1"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
            scheme: HTTPS
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 30
          failureThreshold: 5