apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  annotations:
    opendatahub.io/connections: secret-9k4cep
    opendatahub.io/genai-use-case: chat
    opendatahub.io/hardware-profile-name: g62xlarge-with-nvidia-gpu-l40
    opendatahub.io/hardware-profile-namespace: redhat-ods-applications
    opendatahub.io/hardware-profile-resource-version: '3428520'
    opendatahub.io/model-type: generative
    openshift.io/display-name: RedHatAI/Qwen3-8B-FP8-dynamic Cache-Aware
    security.opendatahub.io/enable-auth: 'false'
  name: redhataiqwen3-8b-fp8-dynamic-ca
  namespace: llmd-demo
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/genai-asset: 'true'
spec:
  model:
    name: redhataiqwen3-8b-fp8-dynamic
    uri: 'oci://registry.redhat.io/rhelai1/modelcar-qwen3-8b-fp8-dynamic:1.5'
  replicas: 3
  router:
    gateway: {}
    route: {}
    scheduler:
      template:
        containers:
          - name: main
            env:
              - name: TOKENIZER_CACHE_DIR
                value: /tmp/tokenizer-cache
              - name: HF_HOME
                value: /tmp/tokenizer-cache
              - name: TRANSFORMERS_CACHE
                value: /tmp/tokenizer-cache
              - name: XDG_CACHE_HOME
                value: /tmp
              - name: LOCAL_TOKENIZER_DIR
                value: /tmp
            args:
              - --pool-group
              - inference.networking.x-k8s.io
              - '--pool-name'
              - '{{ ChildName .ObjectMeta.Name `-inference-pool` }}'
              - '--pool-namespace'
              - '{{ .ObjectMeta.Namespace }}'
              - '--zap-encoder'
              - json
              - '--grpc-port'
              - '9002'
              - '--grpc-health-port'
              - '9003'
              - '--secure-serving'
              - '--model-server-metrics-scheme'
              - https
              - '--config-text'
              - |
                apiVersion: inference.networking.x-k8s.io/v1alpha1
                kind: EndpointPickerConfig
                plugins:
                - type: single-profile-handler
                - type: queue-scorer
                - type: kv-cache-utilization-scorer
                - type: precise-prefix-cache-scorer
                schedulingProfiles:
                - name: default
                  plugins:
                  - pluginRef: queue-scorer
                    weight: 2
                  - pluginRef: kv-cache-utilization-scorer
                    weight: 2
                  - pluginRef: precise-prefix-cache-scorer
                    weight: 3
            volumeMounts:
              - name: tokenizer-cache
                mountPath: /tmp/
              - name: cachi-cache
                mountPath: /cachi2/
        volumes:
          - name: tokenizer-cache
            emptyDir: {}
          - name: cachi-cache
            emptyDir: {}
  template:
    containers:
      - env:
          - name: VLLM_ADDITIONAL_ARGS
            value: '--max-model-len=20000 --enable-prefix-caching'
        name: main
        resources:
          limits:
            cpu: '2'
            memory: 4Gi
            nvidia.com/gpu: '1'
          requests:
            cpu: '2'
            memory: 4Gi
            nvidia.com/gpu: '1'
    nodeSelector:
      node.kubernetes.io/instance-type: g6.2xlarge
    tolerations:
      - effect: NoSchedule
        key: nvida.com/gpu
        operator: Equal
        value: NVIDIA-L40-SHARED